version: '3'

# docker-compose up
# docker rm $(docker ps -a -q) && docker volume prune -f

services:
  mysql:
    container_name: mysql-server-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: golang
    ports:
      - '3306:3306'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'