version: '3.9'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "super_PWD_go"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - './_sql/:/var/lib/mssqlql/data/'
    # command: -c 'opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P super_PWD_go'
